/*
 * Copyright 1999-2023 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.percussion.services.workflow;

import com.percussion.utils.exceptions.PSBaseException;

/**
 * Exceptions generated by the workflow service
 * 
 * @author dougrand
 */
public class PSWorkflowException extends PSBaseException
{
   /**
    * Serial id required for serializable classes 
    */
   private static final long serialVersionUID = 4181855115204766647L;

   /**
    * Construct a workflow exception for messages taking an array of
    * arguments. Be sure to store the arguments in the correct order in
    * the array, where {0} in the string is array element 0, etc.
    *
    * @param msgCode The code of the error string to load.
    *
    * @param arrayArgs The array of arguments to use as the arguments
    *    in the error message.  May be <code>null</code>, and may contain
    *    <code>null</code> elements.
    */
   public PSWorkflowException(int msgCode, Object... arrayArgs) {
      super(msgCode, arrayArgs);
   }

   /**
    * Same as {@link #PSWorkflowException(int, Object...)} but takes one
    * additional parameter to indicate the exception that caused this exception.
    * 
    * @param msgCode The code of the error string to load.
    * @param cause The original exception that caused this exception to be
    *           thrown, may be <code>null</code>.
    * @param arrayArgs The array of arguments to use as the arguments in the
    *           error message. May be <code>null</code>, and may contain
    *           <code>null</code> elements.
    */
   public PSWorkflowException(int msgCode, Throwable cause, Object... arrayArgs) {
      super(msgCode, cause, arrayArgs);
   }

   /**
    * Construct a workflow exception for messages taking no arguments.
    *
    * @param msgCode The error string to load.
    */
   public PSWorkflowException(int msgCode) {
      super(msgCode);
   }

   @Override
   protected String getResourceBundleBaseName()
   {
      return "com.percussion.services.workflow.PSWorkflowErrorStringBundle";
   }

}
