
/*
 *     Percussion CMS
 *     Copyright (C) 1999-2021 Percussion Software, Inc.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     Mailing Address:
 *
 *      Percussion Software, Inc.
 *      PO Box 767
 *      Burlington, MA 01803, USA
 *      +01-781-438-9900
 *      support@percussion.com
 *      https://www.percussion.com
 *
 *     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
 */

package service.web.api.ems.dea;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-07T17:26:49.720-04:00
 * Generated source version: 3.2.4
 *
 */
public final class ServiceSoap_ServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://DEA.EMS.API.Web.Service/", "Service");
    private static final Logger log = LogManager.getLogger(ServiceSoap_ServiceSoap_Client.class);

    private ServiceSoap_ServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                log.error(e.getMessage());
                log.debug(e);
            }
        }

        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap();

        {
        System.out.println("Invoking getCourseBookings...");
        java.lang.String _getCourseBookings_userName = "";
        java.lang.String _getCourseBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getCourseBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getCourseBookings_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getCourseBookings_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getCourseBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getCourseBookings_eventTypes = null;
        boolean _getCourseBookings_viewComboRoomComponents = false;
        java.lang.String _getCourseBookings__return = port.getCourseBookings(_getCourseBookings_userName, _getCourseBookings_password, _getCourseBookings_startDate, _getCourseBookings_endDate, _getCourseBookings_buildings, _getCourseBookings_statuses, _getCourseBookings_eventTypes, _getCourseBookings_viewComboRoomComponents);
        System.out.println("getCourseBookings.result=" + _getCourseBookings__return);


        }
        {
        System.out.println("Invoking getBuildingHours...");
        java.lang.String _getBuildingHours_userName = "";
        java.lang.String _getBuildingHours_password = "";
        service.web.api.ems.dea.ArrayOfInt _getBuildingHours_buildings = null;
        javax.xml.datatype.XMLGregorianCalendar _getBuildingHours_buildingHoursDate = null;
        java.lang.String _getBuildingHours__return = port.getBuildingHours(_getBuildingHours_userName, _getBuildingHours_password, _getBuildingHours_buildings, _getBuildingHours_buildingHoursDate);
        System.out.println("getBuildingHours.result=" + _getBuildingHours__return);


        }
        {
        System.out.println("Invoking getReservationComments...");
        java.lang.String _getReservationComments_userName = "";
        java.lang.String _getReservationComments_password = "";
        int _getReservationComments_reservationID = 0;
        java.lang.String _getReservationComments__return = port.getReservationComments(_getReservationComments_userName, _getReservationComments_password, _getReservationComments_reservationID);
        System.out.println("getReservationComments.result=" + _getReservationComments__return);


        }
        {
        System.out.println("Invoking getBookingHistory...");
        java.lang.String _getBookingHistory_a0 = "";
        java.lang.String _getBookingHistory_a1 = "";
        javax.xml.datatype.XMLGregorianCalendar _getBookingHistory_a2 = null;
        javax.xml.datatype.XMLGregorianCalendar _getBookingHistory_a3 = null;
        service.web.api.ems.dea.ArrayOfInt _getBookingHistory_a4 = null;
        service.web.api.ems.dea.ArrayOfInt _getBookingHistory_a5 = null;
        service.web.api.ems.dea.ArrayOfInt _getBookingHistory_a6 = null;
        service.web.api.ems.dea.ArrayOfInt _getBookingHistory_a7 = null;
        boolean _getBookingHistory_a8 = false;
        java.lang.String _getBookingHistory__return = port.getBookingHistory(_getBookingHistory_a0, _getBookingHistory_a1, _getBookingHistory_a2, _getBookingHistory_a3, _getBookingHistory_a4, _getBookingHistory_a5, _getBookingHistory_a6, _getBookingHistory_a7, _getBookingHistory_a8);
        System.out.println("getBookingHistory.result=" + _getBookingHistory__return);


        }
        {
        System.out.println("Invoking addContact...");
        java.lang.String _addContact_userName = "";
        java.lang.String _addContact_password = "";
        int _addContact_groupID = 0;
        java.lang.String _addContact_contactName = "";
        java.lang.String _addContact_title = "";
        java.lang.String _addContact_address1 = "";
        java.lang.String _addContact_address2 = "";
        java.lang.String _addContact_city = "";
        java.lang.String _addContact_state = "";
        java.lang.String _addContact_zipCode = "";
        java.lang.String _addContact_country = "";
        java.lang.String _addContact_phone = "";
        java.lang.String _addContact_fax = "";
        java.lang.String _addContact_emailAddress = "";
        java.lang.String _addContact_externalReference = "";
        java.lang.String _addContact__return = port.addContact(_addContact_userName, _addContact_password, _addContact_groupID, _addContact_contactName, _addContact_title, _addContact_address1, _addContact_address2, _addContact_city, _addContact_state, _addContact_zipCode, _addContact_country, _addContact_phone, _addContact_fax, _addContact_emailAddress, _addContact_externalReference);
        System.out.println("addContact.result=" + _addContact__return);


        }
        {
        System.out.println("Invoking getAllBookings...");
        java.lang.String _getAllBookings_userName = "";
        java.lang.String _getAllBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getAllBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getAllBookings_endDate = null;
        int _getAllBookings_buildingID = 0;
        boolean _getAllBookings_viewComboRoomComponents = false;
        java.lang.String _getAllBookings__return = port.getAllBookings(_getAllBookings_userName, _getAllBookings_password, _getAllBookings_startDate, _getAllBookings_endDate, _getAllBookings_buildingID, _getAllBookings_viewComboRoomComponents);
        System.out.println("getAllBookings.result=" + _getAllBookings__return);


        }
        {
        System.out.println("Invoking getRoomsBySetupType...");
        java.lang.String _getRoomsBySetupType_userName = "";
        java.lang.String _getRoomsBySetupType_password = "";
        int _getRoomsBySetupType_buildingID = 0;
        int _getRoomsBySetupType_roomTypeID = 0;
        int _getRoomsBySetupType_floorID = 0;
        int _getRoomsBySetupType_setupTypeID = 0;
        java.lang.String _getRoomsBySetupType__return = port.getRoomsBySetupType(_getRoomsBySetupType_userName, _getRoomsBySetupType_password, _getRoomsBySetupType_buildingID, _getRoomsBySetupType_roomTypeID, _getRoomsBySetupType_floorID, _getRoomsBySetupType_setupTypeID);
        System.out.println("getRoomsBySetupType.result=" + _getRoomsBySetupType__return);


        }
        {
        System.out.println("Invoking getWebTemplates...");
        java.lang.String _getWebTemplates_userName = "";
        java.lang.String _getWebTemplates_password = "";
        java.lang.String _getWebTemplates__return = port.getWebTemplates(_getWebTemplates_userName, _getWebTemplates_password);
        System.out.println("getWebTemplates.result=" + _getWebTemplates__return);


        }
        {
        System.out.println("Invoking getAllRooms...");
        java.lang.String _getAllRooms_userName = "";
        java.lang.String _getAllRooms_password = "";
        int _getAllRooms_buildingID = 0;
        java.lang.String _getAllRooms__return = port.getAllRooms(_getAllRooms_userName, _getAllRooms_password, _getAllRooms_buildingID);
        System.out.println("getAllRooms.result=" + _getAllRooms__return);


        }
        {
        System.out.println("Invoking getAllBookings2...");
        java.lang.String _getAllBookings2_userName = "";
        java.lang.String _getAllBookings2_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getAllBookings2_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getAllBookings2_endDate = null;
        int _getAllBookings2_buildingID = 0;
        boolean _getAllBookings2_viewComboRoomComponents = false;
        int _getAllBookings2_udfDefID = 0;
        java.lang.String _getAllBookings2_udfValue = "";
        java.lang.String _getAllBookings2__return = port.getAllBookings2(_getAllBookings2_userName, _getAllBookings2_password, _getAllBookings2_startDate, _getAllBookings2_endDate, _getAllBookings2_buildingID, _getAllBookings2_viewComboRoomComponents, _getAllBookings2_udfDefID, _getAllBookings2_udfValue);
        System.out.println("getAllBookings2.result=" + _getAllBookings2__return);


        }
        {
        System.out.println("Invoking getRooms...");
        java.lang.String _getRooms_userName = "";
        java.lang.String _getRooms_password = "";
        service.web.api.ems.dea.ArrayOfInt _getRooms_buildings = null;
        java.lang.String _getRooms__return = port.getRooms(_getRooms_userName, _getRooms_password, _getRooms_buildings);
        System.out.println("getRooms.result=" + _getRooms__return);


        }
        {
        System.out.println("Invoking getGroupDetails...");
        java.lang.String _getGroupDetails_userName = "";
        java.lang.String _getGroupDetails_password = "";
        int _getGroupDetails_groupID = 0;
        java.lang.String _getGroupDetails__return = port.getGroupDetails(_getGroupDetails_userName, _getGroupDetails_password, _getGroupDetails_groupID);
        System.out.println("getGroupDetails.result=" + _getGroupDetails__return);


        }
        {
        System.out.println("Invoking getContactDetails...");
        java.lang.String _getContactDetails_userName = "";
        java.lang.String _getContactDetails_password = "";
        int _getContactDetails_contactID = 0;
        java.lang.String _getContactDetails__return = port.getContactDetails(_getContactDetails_userName, _getContactDetails_password, _getContactDetails_contactID);
        System.out.println("getContactDetails.result=" + _getContactDetails__return);


        }
        {
        System.out.println("Invoking getReservationSources...");
        java.lang.String _getReservationSources_userName = "";
        java.lang.String _getReservationSources_password = "";
        java.lang.String _getReservationSources__return = port.getReservationSources(_getReservationSources_userName, _getReservationSources_password);
        System.out.println("getReservationSources.result=" + _getReservationSources__return);


        }
        {
        System.out.println("Invoking updateReservation...");
        java.lang.String _updateReservation_userName = "";
        java.lang.String _updateReservation_password = "";
        int _updateReservation_reservationID = 0;
        int _updateReservation_bookingID = 0;
        int _updateReservation_webUserID = 0;
        int _updateReservation_webTemplateID = 0;
        int _updateReservation_reservationSourceID = 0;
        java.lang.String _updateReservation_billingReference = "";
        java.lang.String _updateReservation__return = port.updateReservation(_updateReservation_userName, _updateReservation_password, _updateReservation_reservationID, _updateReservation_bookingID, _updateReservation_webUserID, _updateReservation_webTemplateID, _updateReservation_reservationSourceID, _updateReservation_billingReference);
        System.out.println("updateReservation.result=" + _updateReservation__return);


        }
        {
        System.out.println("Invoking getWebUsers...");
        java.lang.String _getWebUsers_userName = "";
        java.lang.String _getWebUsers_password = "";
        java.lang.String _getWebUsers_webUserName = "";
        java.lang.String _getWebUsers_emailAddress = "";
        java.lang.String _getWebUsers_externalReference = "";
        java.lang.String _getWebUsers_networkID = "";
        java.lang.String _getWebUsers__return = port.getWebUsers(_getWebUsers_userName, _getWebUsers_password, _getWebUsers_webUserName, _getWebUsers_emailAddress, _getWebUsers_externalReference, _getWebUsers_networkID);
        System.out.println("getWebUsers.result=" + _getWebUsers__return);


        }
        {
        System.out.println("Invoking getResources...");
        java.lang.String _getResources_userName = "";
        java.lang.String _getResources_password = "";
        int _getResources_categoryID = 0;
        java.lang.String _getResources__return = port.getResources(_getResources_userName, _getResources_password, _getResources_categoryID);
        System.out.println("getResources.result=" + _getResources__return);


        }
        {
        System.out.println("Invoking addWebUser...");
        java.lang.String _addWebUser_userName = "";
        java.lang.String _addWebUser_password = "";
        java.lang.String _addWebUser_webUserName = "";
        java.lang.String _addWebUser_webUserPassword = "";
        java.lang.String _addWebUser_emailAddress = "";
        java.lang.String _addWebUser_phone = "";
        java.lang.String _addWebUser_fax = "";
        java.lang.String _addWebUser_externalReference = "";
        java.lang.String _addWebUser_networkID = "";
        int _addWebUser_timeZoneID = 0;
        int _addWebUser_statusID = 0;
        int _addWebUser_webSecurityTemplateID = 0;
        service.web.api.ems.dea.ArrayOfInt _addWebUser_webProcessTemplates = null;
        service.web.api.ems.dea.ArrayOfInt _addWebUser_groups = null;
        boolean _addWebUser_validated = false;
        java.lang.String _addWebUser__return = port.addWebUser(_addWebUser_userName, _addWebUser_password, _addWebUser_webUserName, _addWebUser_webUserPassword, _addWebUser_emailAddress, _addWebUser_phone, _addWebUser_fax, _addWebUser_externalReference, _addWebUser_networkID, _addWebUser_timeZoneID, _addWebUser_statusID, _addWebUser_webSecurityTemplateID, _addWebUser_webProcessTemplates, _addWebUser_groups, _addWebUser_validated);
        System.out.println("addWebUser.result=" + _addWebUser__return);


        }
        {
        System.out.println("Invoking getRoomsAvailable...");
        java.lang.String _getRoomsAvailable_userName = "";
        java.lang.String _getRoomsAvailable_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable_bookingDate = null;
        int _getRoomsAvailable_buildingID = 0;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable_endTime = null;
        java.lang.String _getRoomsAvailable__return = port.getRoomsAvailable(_getRoomsAvailable_userName, _getRoomsAvailable_password, _getRoomsAvailable_bookingDate, _getRoomsAvailable_buildingID, _getRoomsAvailable_startTime, _getRoomsAvailable_endTime);
        System.out.println("getRoomsAvailable.result=" + _getRoomsAvailable__return);


        }
        {
        System.out.println("Invoking updateBookingCheckIn...");
        java.lang.String _updateBookingCheckIn_userName = "";
        java.lang.String _updateBookingCheckIn_password = "";
        int _updateBookingCheckIn_bookingID = 0;
        java.lang.String _updateBookingCheckIn__return = port.updateBookingCheckIn(_updateBookingCheckIn_userName, _updateBookingCheckIn_password, _updateBookingCheckIn_bookingID);
        System.out.println("updateBookingCheckIn.result=" + _updateBookingCheckIn__return);


        }
        {
        System.out.println("Invoking getUDFDefinitions...");
        java.lang.String _getUDFDefinitions_userName = "";
        java.lang.String _getUDFDefinitions_password = "";
        java.lang.String _getUDFDefinitions__return = port.getUDFDefinitions(_getUDFDefinitions_userName, _getUDFDefinitions_password);
        System.out.println("getUDFDefinitions.result=" + _getUDFDefinitions__return);


        }
        {
        System.out.println("Invoking getAllComboRoomComponents...");
        java.lang.String _getAllComboRoomComponents_userName = "";
        java.lang.String _getAllComboRoomComponents_password = "";
        java.lang.String _getAllComboRoomComponents__return = port.getAllComboRoomComponents(_getAllComboRoomComponents_userName, _getAllComboRoomComponents_password);
        System.out.println("getAllComboRoomComponents.result=" + _getAllComboRoomComponents__return);


        }
        {
        System.out.println("Invoking getBooking...");
        java.lang.String _getBooking_userName = "";
        java.lang.String _getBooking_password = "";
        int _getBooking_bookingID = 0;
        java.lang.String _getBooking__return = port.getBooking(_getBooking_userName, _getBooking_password, _getBooking_bookingID);
        System.out.println("getBooking.result=" + _getBooking__return);


        }
        {
        System.out.println("Invoking getPricingMethods...");
        java.lang.String _getPricingMethods_userName = "";
        java.lang.String _getPricingMethods_password = "";
        java.lang.String _getPricingMethods__return = port.getPricingMethods(_getPricingMethods_userName, _getPricingMethods_password);
        System.out.println("getPricingMethods.result=" + _getPricingMethods__return);


        }
        {
        System.out.println("Invoking getRoomDetails...");
        java.lang.String _getRoomDetails_userName = "";
        java.lang.String _getRoomDetails_password = "";
        int _getRoomDetails_roomID = 0;
        java.lang.String _getRoomDetails__return = port.getRoomDetails(_getRoomDetails_userName, _getRoomDetails_password, _getRoomDetails_roomID);
        System.out.println("getRoomDetails.result=" + _getRoomDetails__return);


        }
        {
        System.out.println("Invoking getComboRoomComponents...");
        java.lang.String _getComboRoomComponents_userName = "";
        java.lang.String _getComboRoomComponents_password = "";
        int _getComboRoomComponents_roomID = 0;
        java.lang.String _getComboRoomComponents__return = port.getComboRoomComponents(_getComboRoomComponents_userName, _getComboRoomComponents_password, _getComboRoomComponents_roomID);
        System.out.println("getComboRoomComponents.result=" + _getComboRoomComponents__return);


        }
        {
        System.out.println("Invoking getWebUserDetails...");
        java.lang.String _getWebUserDetails_userName = "";
        java.lang.String _getWebUserDetails_password = "";
        int _getWebUserDetails_webUserID = 0;
        java.lang.String _getWebUserDetails__return = port.getWebUserDetails(_getWebUserDetails_userName, _getWebUserDetails_password, _getWebUserDetails_webUserID);
        System.out.println("getWebUserDetails.result=" + _getWebUserDetails__return);


        }
        {
        System.out.println("Invoking getHVACBookings...");
        java.lang.String _getHVACBookings_userName = "";
        java.lang.String _getHVACBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getHVACBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getHVACBookings_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getHVACBookings_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getHVACBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getHVACBookings_eventTypes = null;
        service.web.api.ems.dea.ArrayOfInt _getHVACBookings_groupTypes = null;
        service.web.api.ems.dea.ArrayOfString _getHVACBookings_hvacZones = null;
        boolean _getHVACBookings_viewComboRoomComponents = false;
        java.lang.String _getHVACBookings__return = port.getHVACBookings(_getHVACBookings_userName, _getHVACBookings_password, _getHVACBookings_startDate, _getHVACBookings_endDate, _getHVACBookings_buildings, _getHVACBookings_statuses, _getHVACBookings_eventTypes, _getHVACBookings_groupTypes, _getHVACBookings_hvacZones, _getHVACBookings_viewComboRoomComponents);
        System.out.println("getHVACBookings.result=" + _getHVACBookings__return);


        }
        {
        System.out.println("Invoking addReservation4...");
        java.lang.String _addReservation4_userName = "";
        java.lang.String _addReservation4_password = "";
        int _addReservation4_groupID = 0;
        int _addReservation4_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addReservation4_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation4_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation4_endTime = null;
        java.lang.String _addReservation4_eventName = "";
        int _addReservation4_statusID = 0;
        int _addReservation4_eventTypeID = 0;
        int _addReservation4_webUserID = 0;
        int _addReservation4_webTemplateID = 0;
        int _addReservation4_reservationSourceID = 0;
        java.lang.String _addReservation4_billingReference = "";
        java.lang.String _addReservation4__return = port.addReservation4(_addReservation4_userName, _addReservation4_password, _addReservation4_groupID, _addReservation4_roomID, _addReservation4_bookingDate, _addReservation4_startTime, _addReservation4_endTime, _addReservation4_eventName, _addReservation4_statusID, _addReservation4_eventTypeID, _addReservation4_webUserID, _addReservation4_webTemplateID, _addReservation4_reservationSourceID, _addReservation4_billingReference);
        System.out.println("addReservation4.result=" + _addReservation4__return);


        }
        {
        System.out.println("Invoking getWebUserOptions...");
        java.lang.String _getWebUserOptions_userName = "";
        java.lang.String _getWebUserOptions_password = "";
        int _getWebUserOptions_webUserID = 0;
        java.lang.String _getWebUserOptions__return = port.getWebUserOptions(_getWebUserOptions_userName, _getWebUserOptions_password, _getWebUserOptions_webUserID);
        System.out.println("getWebUserOptions.result=" + _getWebUserOptions__return);


        }
        {
        System.out.println("Invoking getRoomBookings...");
        java.lang.String _getRoomBookings_userName = "";
        java.lang.String _getRoomBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getRoomBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomBookings_endDate = null;
        int _getRoomBookings_roomID = 0;
        service.web.api.ems.dea.ArrayOfInt _getRoomBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getRoomBookings_eventTypes = null;
        service.web.api.ems.dea.ArrayOfInt _getRoomBookings_groupTypes = null;
        boolean _getRoomBookings_viewComboRoomComponents = false;
        java.lang.String _getRoomBookings__return = port.getRoomBookings(_getRoomBookings_userName, _getRoomBookings_password, _getRoomBookings_startDate, _getRoomBookings_endDate, _getRoomBookings_roomID, _getRoomBookings_statuses, _getRoomBookings_eventTypes, _getRoomBookings_groupTypes, _getRoomBookings_viewComboRoomComponents);
        System.out.println("getRoomBookings.result=" + _getRoomBookings__return);


        }
        {
        System.out.println("Invoking addReservation3...");
        java.lang.String _addReservation3_userName = "";
        java.lang.String _addReservation3_password = "";
        int _addReservation3_groupID = 0;
        int _addReservation3_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addReservation3_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation3_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation3_endTime = null;
        java.lang.String _addReservation3_eventName = "";
        int _addReservation3_statusID = 0;
        int _addReservation3_eventTypeID = 0;
        int _addReservation3_webUserID = 0;
        int _addReservation3_webTemplateID = 0;
        int _addReservation3_reservationSourceID = 0;
        java.lang.String _addReservation3__return = port.addReservation3(_addReservation3_userName, _addReservation3_password, _addReservation3_groupID, _addReservation3_roomID, _addReservation3_bookingDate, _addReservation3_startTime, _addReservation3_endTime, _addReservation3_eventName, _addReservation3_statusID, _addReservation3_eventTypeID, _addReservation3_webUserID, _addReservation3_webTemplateID, _addReservation3_reservationSourceID);
        System.out.println("addReservation3.result=" + _addReservation3__return);


        }
        {
        System.out.println("Invoking addReservation5...");
        java.lang.String _addReservation5_userName = "";
        java.lang.String _addReservation5_password = "";
        int _addReservation5_groupID = 0;
        int _addReservation5_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addReservation5_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation5_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation5_endTime = null;
        java.lang.String _addReservation5_eventName = "";
        int _addReservation5_statusID = 0;
        int _addReservation5_eventTypeID = 0;
        int _addReservation5_webUserID = 0;
        int _addReservation5_webTemplateID = 0;
        int _addReservation5_reservationSourceID = 0;
        java.lang.String _addReservation5_billingReference = "";
        java.lang.String _addReservation5_poNumber = "";
        int _addReservation5_setupCount = 0;
        java.lang.String _addReservation5__return = port.addReservation5(_addReservation5_userName, _addReservation5_password, _addReservation5_groupID, _addReservation5_roomID, _addReservation5_bookingDate, _addReservation5_startTime, _addReservation5_endTime, _addReservation5_eventName, _addReservation5_statusID, _addReservation5_eventTypeID, _addReservation5_webUserID, _addReservation5_webTemplateID, _addReservation5_reservationSourceID, _addReservation5_billingReference, _addReservation5_poNumber, _addReservation5_setupCount);
        System.out.println("addReservation5.result=" + _addReservation5__return);


        }
        {
        System.out.println("Invoking getGroupTypes...");
        java.lang.String _getGroupTypes_userName = "";
        java.lang.String _getGroupTypes_password = "";
        java.lang.String _getGroupTypes__return = port.getGroupTypes(_getGroupTypes_userName, _getGroupTypes_password);
        System.out.println("getGroupTypes.result=" + _getGroupTypes__return);


        }
        {
        System.out.println("Invoking updateBooking2...");
        java.lang.String _updateBooking2_userName = "";
        java.lang.String _updateBooking2_password = "";
        int _updateBooking2_bookingID = 0;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking2_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking2_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking2_endTime = null;
        int _updateBooking2_statusID = 0;
        int _updateBooking2_roomID = 0;
        java.lang.String _updateBooking2_eventName = "";
        java.lang.String _updateBooking2__return = port.updateBooking2(_updateBooking2_userName, _updateBooking2_password, _updateBooking2_bookingID, _updateBooking2_bookingDate, _updateBooking2_startTime, _updateBooking2_endTime, _updateBooking2_statusID, _updateBooking2_roomID, _updateBooking2_eventName);
        System.out.println("updateBooking2.result=" + _updateBooking2__return);


        }
        {
        System.out.println("Invoking addReservation...");
        java.lang.String _addReservation_userName = "";
        java.lang.String _addReservation_password = "";
        int _addReservation_groupID = 0;
        int _addReservation_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addReservation_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation_endTime = null;
        java.lang.String _addReservation_eventName = "";
        int _addReservation_statusID = 0;
        java.lang.String _addReservation__return = port.addReservation(_addReservation_userName, _addReservation_password, _addReservation_groupID, _addReservation_roomID, _addReservation_bookingDate, _addReservation_startTime, _addReservation_endTime, _addReservation_eventName, _addReservation_statusID);
        System.out.println("addReservation.result=" + _addReservation__return);


        }
        {
        System.out.println("Invoking getWebSecurityTemplateRoles...");
        java.lang.String _getWebSecurityTemplateRoles_userName = "";
        java.lang.String _getWebSecurityTemplateRoles_password = "";
        int _getWebSecurityTemplateRoles_webSecurityTemplateID = 0;
        java.lang.String _getWebSecurityTemplateRoles__return = port.getWebSecurityTemplateRoles(_getWebSecurityTemplateRoles_userName, _getWebSecurityTemplateRoles_password, _getWebSecurityTemplateRoles_webSecurityTemplateID);
        System.out.println("getWebSecurityTemplateRoles.result=" + _getWebSecurityTemplateRoles__return);


        }
        {
        System.out.println("Invoking getStatuses...");
        java.lang.String _getStatuses_userName = "";
        java.lang.String _getStatuses_password = "";
        java.lang.String _getStatuses__return = port.getStatuses(_getStatuses_userName, _getStatuses_password);
        System.out.println("getStatuses.result=" + _getStatuses__return);


        }
        {
        System.out.println("Invoking getEventTypes...");
        java.lang.String _getEventTypes_userName = "";
        java.lang.String _getEventTypes_password = "";
        java.lang.String _getEventTypes__return = port.getEventTypes(_getEventTypes_userName, _getEventTypes_password);
        System.out.println("getEventTypes.result=" + _getEventTypes__return);


        }
        {
        System.out.println("Invoking addGroup...");
        java.lang.String _addGroup_userName = "";
        java.lang.String _addGroup_password = "";
        java.lang.String _addGroup_groupName = "";
        int _addGroup_groupTypeID = 0;
        java.lang.String _addGroup_address1 = "";
        java.lang.String _addGroup_address2 = "";
        java.lang.String _addGroup_city = "";
        java.lang.String _addGroup_state = "";
        java.lang.String _addGroup_zipCode = "";
        java.lang.String _addGroup_country = "";
        java.lang.String _addGroup_phone = "";
        java.lang.String _addGroup_fax = "";
        java.lang.String _addGroup_emailAddress = "";
        java.lang.String _addGroup_externalReference = "";
        java.lang.String _addGroup__return = port.addGroup(_addGroup_userName, _addGroup_password, _addGroup_groupName, _addGroup_groupTypeID, _addGroup_address1, _addGroup_address2, _addGroup_city, _addGroup_state, _addGroup_zipCode, _addGroup_country, _addGroup_phone, _addGroup_fax, _addGroup_emailAddress, _addGroup_externalReference);
        System.out.println("addGroup.result=" + _addGroup__return);


        }
        {
        System.out.println("Invoking addReservation2...");
        java.lang.String _addReservation2_userName = "";
        java.lang.String _addReservation2_password = "";
        int _addReservation2_groupID = 0;
        int _addReservation2_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addReservation2_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation2_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addReservation2_endTime = null;
        java.lang.String _addReservation2_eventName = "";
        int _addReservation2_statusID = 0;
        int _addReservation2_eventTypeID = 0;
        int _addReservation2_webUserID = 0;
        int _addReservation2_webTemplateID = 0;
        java.lang.String _addReservation2__return = port.addReservation2(_addReservation2_userName, _addReservation2_password, _addReservation2_groupID, _addReservation2_roomID, _addReservation2_bookingDate, _addReservation2_startTime, _addReservation2_endTime, _addReservation2_eventName, _addReservation2_statusID, _addReservation2_eventTypeID, _addReservation2_webUserID, _addReservation2_webTemplateID);
        System.out.println("addReservation2.result=" + _addReservation2__return);


        }
        {
        System.out.println("Invoking updateContact...");
        java.lang.String _updateContact_userName = "";
        java.lang.String _updateContact_password = "";
        int _updateContact_contactID = 0;
        java.lang.String _updateContact_contactName = "";
        java.lang.String _updateContact_title = "";
        java.lang.String _updateContact_address1 = "";
        java.lang.String _updateContact_address2 = "";
        java.lang.String _updateContact_city = "";
        java.lang.String _updateContact_state = "";
        java.lang.String _updateContact_zipCode = "";
        java.lang.String _updateContact_country = "";
        java.lang.String _updateContact_phone = "";
        java.lang.String _updateContact_fax = "";
        java.lang.String _updateContact_emailAddress = "";
        java.lang.String _updateContact_externalReference = "";
        boolean _updateContact_active = false;
        java.lang.String _updateContact__return = port.updateContact(_updateContact_userName, _updateContact_password, _updateContact_contactID, _updateContact_contactName, _updateContact_title, _updateContact_address1, _updateContact_address2, _updateContact_city, _updateContact_state, _updateContact_zipCode, _updateContact_country, _updateContact_phone, _updateContact_fax, _updateContact_emailAddress, _updateContact_externalReference, _updateContact_active);
        System.out.println("updateContact.result=" + _updateContact__return);


        }
        {
        System.out.println("Invoking addServiceOrder...");
        java.lang.String _addServiceOrder_userName = "";
        java.lang.String _addServiceOrder_password = "";
        int _addServiceOrder_categoryID = 0;
        int _addServiceOrder_bookingID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addServiceOrder_timeStart = null;
        javax.xml.datatype.XMLGregorianCalendar _addServiceOrder_timeEnd = null;
        int _addServiceOrder_serviceTypeID = 0;
        int _addServiceOrder_stateID = 0;
        int _addServiceOrder_estimatedCount = 0;
        int _addServiceOrder_guaranteedCount = 0;
        int _addServiceOrder_actualCount = 0;
        java.lang.String _addServiceOrder__return = port.addServiceOrder(_addServiceOrder_userName, _addServiceOrder_password, _addServiceOrder_categoryID, _addServiceOrder_bookingID, _addServiceOrder_timeStart, _addServiceOrder_timeEnd, _addServiceOrder_serviceTypeID, _addServiceOrder_stateID, _addServiceOrder_estimatedCount, _addServiceOrder_guaranteedCount, _addServiceOrder_actualCount);
        System.out.println("addServiceOrder.result=" + _addServiceOrder__return);


        }
        {
        System.out.println("Invoking getRoomAvailability...");
        java.lang.String _getRoomAvailability_userName = "";
        java.lang.String _getRoomAvailability_password = "";
        int _getRoomAvailability_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _getRoomAvailability_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomAvailability_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomAvailability_endTime = null;
        java.lang.String _getRoomAvailability__return = port.getRoomAvailability(_getRoomAvailability_userName, _getRoomAvailability_password, _getRoomAvailability_roomID, _getRoomAvailability_bookingDate, _getRoomAvailability_startTime, _getRoomAvailability_endTime);
        System.out.println("getRoomAvailability.result=" + _getRoomAvailability__return);


        }
        {
        System.out.println("Invoking getContacts...");
        java.lang.String _getContacts_userName = "";
        java.lang.String _getContacts_password = "";
        int _getContacts_groupID = 0;
        java.lang.String _getContacts__return = port.getContacts(_getContacts_userName, _getContacts_password, _getContacts_groupID);
        System.out.println("getContacts.result=" + _getContacts__return);


        }
        {
        System.out.println("Invoking getBookings...");
        java.lang.String _getBookings_userName = "";
        java.lang.String _getBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getBookings_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings_eventTypes = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings_groupTypes = null;
        boolean _getBookings_viewComboRoomComponents = false;
        java.lang.String _getBookings__return = port.getBookings(_getBookings_userName, _getBookings_password, _getBookings_startDate, _getBookings_endDate, _getBookings_buildings, _getBookings_statuses, _getBookings_eventTypes, _getBookings_groupTypes, _getBookings_viewComboRoomComponents);
        System.out.println("getBookings.result=" + _getBookings__return);


        }
        {
        System.out.println("Invoking getBuildingHolidays...");
        java.lang.String _getBuildingHolidays_userName = "";
        java.lang.String _getBuildingHolidays_password = "";
        service.web.api.ems.dea.ArrayOfInt _getBuildingHolidays_buildings = null;
        javax.xml.datatype.XMLGregorianCalendar _getBuildingHolidays_holidayDate = null;
        java.lang.String _getBuildingHolidays__return = port.getBuildingHolidays(_getBuildingHolidays_userName, _getBuildingHolidays_password, _getBuildingHolidays_buildings, _getBuildingHolidays_holidayDate);
        System.out.println("getBuildingHolidays.result=" + _getBuildingHolidays__return);


        }
        {
        System.out.println("Invoking getWebUserBookings...");
        java.lang.String _getWebUserBookings_userName = "";
        java.lang.String _getWebUserBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getWebUserBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getWebUserBookings_endDate = null;
        int _getWebUserBookings_webUserID = 0;
        service.web.api.ems.dea.ArrayOfInt _getWebUserBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getWebUserBookings_statusTypes = null;
        boolean _getWebUserBookings_viewComboRoomComponents = false;
        java.lang.String _getWebUserBookings__return = port.getWebUserBookings(_getWebUserBookings_userName, _getWebUserBookings_password, _getWebUserBookings_startDate, _getWebUserBookings_endDate, _getWebUserBookings_webUserID, _getWebUserBookings_statuses, _getWebUserBookings_statusTypes, _getWebUserBookings_viewComboRoomComponents);
        System.out.println("getWebUserBookings.result=" + _getWebUserBookings__return);


        }
        {
        System.out.println("Invoking updateServiceOrderDetail...");
        java.lang.String _updateServiceOrderDetail_userName = "";
        java.lang.String _updateServiceOrderDetail_password = "";
        int _updateServiceOrderDetail_serviceOrderDetailID = 0;
        int _updateServiceOrderDetail_resourceID = 0;
        java.math.BigDecimal _updateServiceOrderDetail_quantity = new java.math.BigDecimal("0");
        int _updateServiceOrderDetail_pricingMethodID = 0;
        java.math.BigDecimal _updateServiceOrderDetail_unitPrice = new java.math.BigDecimal("0");
        java.lang.String _updateServiceOrderDetail_notes = "";
        java.lang.String _updateServiceOrderDetail_specialInstructions = "";
        java.lang.String _updateServiceOrderDetail__return = port.updateServiceOrderDetail(_updateServiceOrderDetail_userName, _updateServiceOrderDetail_password, _updateServiceOrderDetail_serviceOrderDetailID, _updateServiceOrderDetail_resourceID, _updateServiceOrderDetail_quantity, _updateServiceOrderDetail_pricingMethodID, _updateServiceOrderDetail_unitPrice, _updateServiceOrderDetail_notes, _updateServiceOrderDetail_specialInstructions);
        System.out.println("updateServiceOrderDetail.result=" + _updateServiceOrderDetail__return);


        }
        {
        System.out.println("Invoking getChangedBookings...");
        java.lang.String _getChangedBookings_userName = "";
        java.lang.String _getChangedBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getChangedBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getChangedBookings_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getChangedBookings_rooms = null;
        service.web.api.ems.dea.ArrayOfInt _getChangedBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getChangedBookings_eventTypes = null;
        service.web.api.ems.dea.ArrayOfInt _getChangedBookings_groupTypes = null;
        boolean _getChangedBookings_viewComboRoomComponents = false;
        java.lang.String _getChangedBookings__return = port.getChangedBookings(_getChangedBookings_userName, _getChangedBookings_password, _getChangedBookings_startDate, _getChangedBookings_endDate, _getChangedBookings_rooms, _getChangedBookings_statuses, _getChangedBookings_eventTypes, _getChangedBookings_groupTypes, _getChangedBookings_viewComboRoomComponents);
        System.out.println("getChangedBookings.result=" + _getChangedBookings__return);


        }
        {
        System.out.println("Invoking getCategories...");
        java.lang.String _getCategories_userName = "";
        java.lang.String _getCategories_password = "";
        int _getCategories_buildingID = 0;
        java.lang.String _getCategories__return = port.getCategories(_getCategories_userName, _getCategories_password, _getCategories_buildingID);
        System.out.println("getCategories.result=" + _getCategories__return);


        }
        {
        System.out.println("Invoking getServiceOrderDetails2...");
        java.lang.String _getServiceOrderDetails2_userName = "";
        java.lang.String _getServiceOrderDetails2_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getServiceOrderDetails2_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getServiceOrderDetails2_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getServiceOrderDetails2_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getServiceOrderDetails2_statuses = null;
        java.lang.String _getServiceOrderDetails2__return = port.getServiceOrderDetails2(_getServiceOrderDetails2_userName, _getServiceOrderDetails2_password, _getServiceOrderDetails2_startDate, _getServiceOrderDetails2_endDate, _getServiceOrderDetails2_buildings, _getServiceOrderDetails2_statuses);
        System.out.println("getServiceOrderDetails2.result=" + _getServiceOrderDetails2__return);


        }
        {
        System.out.println("Invoking getWebProcessTemplateCategories...");
        java.lang.String _getWebProcessTemplateCategories_userName = "";
        java.lang.String _getWebProcessTemplateCategories_password = "";
        int _getWebProcessTemplateCategories_webProcessTemplateID = 0;
        java.lang.String _getWebProcessTemplateCategories__return = port.getWebProcessTemplateCategories(_getWebProcessTemplateCategories_userName, _getWebProcessTemplateCategories_password, _getWebProcessTemplateCategories_webProcessTemplateID);
        System.out.println("getWebProcessTemplateCategories.result=" + _getWebProcessTemplateCategories__return);


        }
        {
        System.out.println("Invoking getBookings2...");
        java.lang.String _getBookings2_userName = "";
        java.lang.String _getBookings2_password = "";
        int _getBookings2_reservationID = 0;
        javax.xml.datatype.XMLGregorianCalendar _getBookings2_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getBookings2_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings2_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings2_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings2_eventTypes = null;
        service.web.api.ems.dea.ArrayOfInt _getBookings2_groupTypes = null;
        boolean _getBookings2_viewComboRoomComponents = false;
        java.lang.String _getBookings2__return = port.getBookings2(_getBookings2_userName, _getBookings2_password, _getBookings2_reservationID, _getBookings2_startDate, _getBookings2_endDate, _getBookings2_buildings, _getBookings2_statuses, _getBookings2_eventTypes, _getBookings2_groupTypes, _getBookings2_viewComboRoomComponents);
        System.out.println("getBookings2.result=" + _getBookings2__return);


        }
        {
        System.out.println("Invoking addWebRequest...");
        java.lang.String _addWebRequest_userName = "";
        java.lang.String _addWebRequest_password = "";
        java.lang.String _addWebRequest_eventName = "";
        int _addWebRequest_eventTypeID = 0;
        java.lang.String _addWebRequest_groupName = "";
        java.lang.String _addWebRequest_contact = "";
        java.lang.String _addWebRequest_phone = "";
        java.lang.String _addWebRequest_fax = "";
        java.lang.String _addWebRequest_emailAddress = "";
        int _addWebRequest_webUserID = 0;
        int _addWebRequest_buildingID = 0;
        int _addWebRequest_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addWebRequest_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addWebRequest_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addWebRequest_endTime = null;
        int _addWebRequest_setupTypeID = 0;
        int _addWebRequest_setupCount = 0;
        java.lang.String _addWebRequest_notes = "";
        java.lang.String _addWebRequest__return = port.addWebRequest(_addWebRequest_userName, _addWebRequest_password, _addWebRequest_eventName, _addWebRequest_eventTypeID, _addWebRequest_groupName, _addWebRequest_contact, _addWebRequest_phone, _addWebRequest_fax, _addWebRequest_emailAddress, _addWebRequest_webUserID, _addWebRequest_buildingID, _addWebRequest_roomID, _addWebRequest_bookingDate, _addWebRequest_startTime, _addWebRequest_endTime, _addWebRequest_setupTypeID, _addWebRequest_setupCount, _addWebRequest_notes);
        System.out.println("addWebRequest.result=" + _addWebRequest__return);


        }
        {
        System.out.println("Invoking getAPIVersion...");
        java.lang.String _getAPIVersion__return = port.getAPIVersion();
        System.out.println("getAPIVersion.result=" + _getAPIVersion__return);


        }
        {
        System.out.println("Invoking updateUDF...");
        java.lang.String _updateUDF_userName = "";
        java.lang.String _updateUDF_password = "";
        int _updateUDF_udfid = 0;
        java.lang.String _updateUDF_udfValue = "";
        java.lang.String _updateUDF__return = port.updateUDF(_updateUDF_userName, _updateUDF_password, _updateUDF_udfid, _updateUDF_udfValue);
        System.out.println("updateUDF.result=" + _updateUDF__return);


        }
        {
        System.out.println("Invoking updateServiceOrder...");
        java.lang.String _updateServiceOrder_userName = "";
        java.lang.String _updateServiceOrder_password = "";
        int _updateServiceOrder_serviceOrderID = 0;
        javax.xml.datatype.XMLGregorianCalendar _updateServiceOrder_timeStart = null;
        javax.xml.datatype.XMLGregorianCalendar _updateServiceOrder_timeEnd = null;
        int _updateServiceOrder_stateID = 0;
        int _updateServiceOrder_serviceTypeID = 0;
        int _updateServiceOrder_estimatedCount = 0;
        int _updateServiceOrder_guaranteedCount = 0;
        int _updateServiceOrder_actualCount = 0;
        java.lang.String _updateServiceOrder__return = port.updateServiceOrder(_updateServiceOrder_userName, _updateServiceOrder_password, _updateServiceOrder_serviceOrderID, _updateServiceOrder_timeStart, _updateServiceOrder_timeEnd, _updateServiceOrder_stateID, _updateServiceOrder_serviceTypeID, _updateServiceOrder_estimatedCount, _updateServiceOrder_guaranteedCount, _updateServiceOrder_actualCount);
        System.out.println("updateServiceOrder.result=" + _updateServiceOrder__return);


        }
        {
        System.out.println("Invoking getServiceOrderDetails...");
        java.lang.String _getServiceOrderDetails_userName = "";
        java.lang.String _getServiceOrderDetails_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getServiceOrderDetails_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getServiceOrderDetails_endDate = null;
        service.web.api.ems.dea.ArrayOfInt _getServiceOrderDetails_buildings = null;
        service.web.api.ems.dea.ArrayOfInt _getServiceOrderDetails_statuses = null;
        java.lang.String _getServiceOrderDetails__return = port.getServiceOrderDetails(_getServiceOrderDetails_userName, _getServiceOrderDetails_password, _getServiceOrderDetails_startDate, _getServiceOrderDetails_endDate, _getServiceOrderDetails_buildings, _getServiceOrderDetails_statuses);
        System.out.println("getServiceOrderDetails.result=" + _getServiceOrderDetails__return);


        }
        {
        System.out.println("Invoking getSetupTypes...");
        java.lang.String _getSetupTypes_userName = "";
        java.lang.String _getSetupTypes_password = "";
        java.lang.String _getSetupTypes__return = port.getSetupTypes(_getSetupTypes_userName, _getSetupTypes_password);
        System.out.println("getSetupTypes.result=" + _getSetupTypes__return);


        }
        {
        System.out.println("Invoking getRoomTypesByWPT...");
        java.lang.String _getRoomTypesByWPT_userName = "";
        java.lang.String _getRoomTypesByWPT_password = "";
        service.web.api.ems.dea.ArrayOfInt _getRoomTypesByWPT_webProcessTemplates = null;
        service.web.api.ems.dea.ArrayOfInt _getRoomTypesByWPT_buildings = null;
        java.lang.String _getRoomTypesByWPT__return = port.getRoomTypesByWPT(_getRoomTypesByWPT_userName, _getRoomTypesByWPT_password, _getRoomTypesByWPT_webProcessTemplates, _getRoomTypesByWPT_buildings);
        System.out.println("getRoomTypesByWPT.result=" + _getRoomTypesByWPT__return);


        }
        {
        System.out.println("Invoking getWebUserWebProcessTemplates...");
        java.lang.String _getWebUserWebProcessTemplates_userName = "";
        java.lang.String _getWebUserWebProcessTemplates_password = "";
        int _getWebUserWebProcessTemplates_webUserID = 0;
        java.lang.String _getWebUserWebProcessTemplates__return = port.getWebUserWebProcessTemplates(_getWebUserWebProcessTemplates_userName, _getWebUserWebProcessTemplates_password, _getWebUserWebProcessTemplates_webUserID);
        System.out.println("getWebUserWebProcessTemplates.result=" + _getWebUserWebProcessTemplates__return);


        }
        {
        System.out.println("Invoking addServiceOrderDetail...");
        java.lang.String _addServiceOrderDetail_userName = "";
        java.lang.String _addServiceOrderDetail_password = "";
        int _addServiceOrderDetail_serviceOrderID = 0;
        int _addServiceOrderDetail_resourceID = 0;
        java.math.BigDecimal _addServiceOrderDetail_quantity = new java.math.BigDecimal("0");
        int _addServiceOrderDetail_pricingMethodID = 0;
        java.math.BigDecimal _addServiceOrderDetail_unitPrice = new java.math.BigDecimal("0");
        java.lang.String _addServiceOrderDetail_notes = "";
        java.lang.String _addServiceOrderDetail_specialInstructions = "";
        java.lang.String _addServiceOrderDetail__return = port.addServiceOrderDetail(_addServiceOrderDetail_userName, _addServiceOrderDetail_password, _addServiceOrderDetail_serviceOrderID, _addServiceOrderDetail_resourceID, _addServiceOrderDetail_quantity, _addServiceOrderDetail_pricingMethodID, _addServiceOrderDetail_unitPrice, _addServiceOrderDetail_notes, _addServiceOrderDetail_specialInstructions);
        System.out.println("addServiceOrderDetail.result=" + _addServiceOrderDetail__return);


        }
        {
        System.out.println("Invoking getGroupBookings...");
        java.lang.String _getGroupBookings_userName = "";
        java.lang.String _getGroupBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getGroupBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getGroupBookings_endDate = null;
        int _getGroupBookings_groupID = 0;
        service.web.api.ems.dea.ArrayOfInt _getGroupBookings_statuses = null;
        service.web.api.ems.dea.ArrayOfInt _getGroupBookings_statusTypes = null;
        boolean _getGroupBookings_viewComboRoomComponents = false;
        java.lang.String _getGroupBookings__return = port.getGroupBookings(_getGroupBookings_userName, _getGroupBookings_password, _getGroupBookings_startDate, _getGroupBookings_endDate, _getGroupBookings_groupID, _getGroupBookings_statuses, _getGroupBookings_statusTypes, _getGroupBookings_viewComboRoomComponents);
        System.out.println("getGroupBookings.result=" + _getGroupBookings__return);


        }
        {
        System.out.println("Invoking getBookingCheckIn...");
        java.lang.String _getBookingCheckIn_userName = "";
        java.lang.String _getBookingCheckIn_password = "";
        int _getBookingCheckIn_bookingID = 0;
        java.lang.String _getBookingCheckIn__return = port.getBookingCheckIn(_getBookingCheckIn_userName, _getBookingCheckIn_password, _getBookingCheckIn_bookingID);
        System.out.println("getBookingCheckIn.result=" + _getBookingCheckIn__return);


        }
        {
        System.out.println("Invoking getRoomsAvailable2...");
        java.lang.String _getRoomsAvailable2_userName = "";
        java.lang.String _getRoomsAvailable2_password = "";
        int _getRoomsAvailable2_buildingID = 0;
        int _getRoomsAvailable2_roomTypeID = 0;
        int _getRoomsAvailable2_floorID = 0;
        service.web.api.ems.dea.ArrayOfInt _getRoomsAvailable2_webProcessTemplates = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable2_startDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable2_endDateTime = null;
        java.lang.String _getRoomsAvailable2__return = port.getRoomsAvailable2(_getRoomsAvailable2_userName, _getRoomsAvailable2_password, _getRoomsAvailable2_buildingID, _getRoomsAvailable2_roomTypeID, _getRoomsAvailable2_floorID, _getRoomsAvailable2_webProcessTemplates, _getRoomsAvailable2_startDateTime, _getRoomsAvailable2_endDateTime);
        System.out.println("getRoomsAvailable2.result=" + _getRoomsAvailable2__return);


        }
        {
        System.out.println("Invoking updateGroup...");
        java.lang.String _updateGroup_userName = "";
        java.lang.String _updateGroup_password = "";
        int _updateGroup_groupID = 0;
        java.lang.String _updateGroup_groupName = "";
        int _updateGroup_groupTypeID = 0;
        java.lang.String _updateGroup_address1 = "";
        java.lang.String _updateGroup_address2 = "";
        java.lang.String _updateGroup_city = "";
        java.lang.String _updateGroup_state = "";
        java.lang.String _updateGroup_zipCode = "";
        java.lang.String _updateGroup_country = "";
        java.lang.String _updateGroup_phone = "";
        java.lang.String _updateGroup_fax = "";
        java.lang.String _updateGroup_emailAddress = "";
        java.lang.String _updateGroup_externalReference = "";
        boolean _updateGroup_active = false;
        java.lang.String _updateGroup__return = port.updateGroup(_updateGroup_userName, _updateGroup_password, _updateGroup_groupID, _updateGroup_groupName, _updateGroup_groupTypeID, _updateGroup_address1, _updateGroup_address2, _updateGroup_city, _updateGroup_state, _updateGroup_zipCode, _updateGroup_country, _updateGroup_phone, _updateGroup_fax, _updateGroup_emailAddress, _updateGroup_externalReference, _updateGroup_active);
        System.out.println("updateGroup.result=" + _updateGroup__return);


        }
        {
        System.out.println("Invoking getWebProcessTemplateSettings...");
        java.lang.String _getWebProcessTemplateSettings_userName = "";
        java.lang.String _getWebProcessTemplateSettings_password = "";
        int _getWebProcessTemplateSettings_webProcessTemplateID = 0;
        java.lang.String _getWebProcessTemplateSettings__return = port.getWebProcessTemplateSettings(_getWebProcessTemplateSettings_userName, _getWebProcessTemplateSettings_password, _getWebProcessTemplateSettings_webProcessTemplateID);
        System.out.println("getWebProcessTemplateSettings.result=" + _getWebProcessTemplateSettings__return);


        }
        {
        System.out.println("Invoking updateBooking...");
        java.lang.String _updateBooking_userName = "";
        java.lang.String _updateBooking_password = "";
        int _updateBooking_bookingID = 0;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _updateBooking_endTime = null;
        int _updateBooking_statusID = 0;
        int _updateBooking_roomID = 0;
        java.lang.String _updateBooking__return = port.updateBooking(_updateBooking_userName, _updateBooking_password, _updateBooking_bookingID, _updateBooking_bookingDate, _updateBooking_startTime, _updateBooking_endTime, _updateBooking_statusID, _updateBooking_roomID);
        System.out.println("updateBooking.result=" + _updateBooking__return);


        }
        {
        System.out.println("Invoking getRoomsAvailable3...");
        java.lang.String _getRoomsAvailable3_userName = "";
        java.lang.String _getRoomsAvailable3_password = "";
        int _getRoomsAvailable3_buildingID = 0;
        int _getRoomsAvailable3_roomTypeID = 0;
        int _getRoomsAvailable3_floorID = 0;
        service.web.api.ems.dea.ArrayOfInt _getRoomsAvailable3_webProcessTemplates = null;
        service.web.api.ems.dea.ArrayOfInt _getRoomsAvailable3_features = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable3_startDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable3_endDateTime = null;
        java.lang.String _getRoomsAvailable3__return = port.getRoomsAvailable3(_getRoomsAvailable3_userName, _getRoomsAvailable3_password, _getRoomsAvailable3_buildingID, _getRoomsAvailable3_roomTypeID, _getRoomsAvailable3_floorID, _getRoomsAvailable3_webProcessTemplates, _getRoomsAvailable3_features, _getRoomsAvailable3_startDateTime, _getRoomsAvailable3_endDateTime);
        System.out.println("getRoomsAvailable3.result=" + _getRoomsAvailable3__return);


        }
        {
        System.out.println("Invoking getRoomsAvailable4...");
        java.lang.String _getRoomsAvailable4_userName = "";
        java.lang.String _getRoomsAvailable4_password = "";
        int _getRoomsAvailable4_buildingID = 0;
        int _getRoomsAvailable4_roomTypeID = 0;
        int _getRoomsAvailable4_floorID = 0;
        service.web.api.ems.dea.ArrayOfInt _getRoomsAvailable4_webProcessTemplates = null;
        int _getRoomsAvailable4_setupTypeId = 0;
        int _getRoomsAvailable4_requestedCapacity = 0;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable4_startDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getRoomsAvailable4_endDateTime = null;
        java.lang.String _getRoomsAvailable4__return = port.getRoomsAvailable4(_getRoomsAvailable4_userName, _getRoomsAvailable4_password, _getRoomsAvailable4_buildingID, _getRoomsAvailable4_roomTypeID, _getRoomsAvailable4_floorID, _getRoomsAvailable4_webProcessTemplates, _getRoomsAvailable4_setupTypeId, _getRoomsAvailable4_requestedCapacity, _getRoomsAvailable4_startDateTime, _getRoomsAvailable4_endDateTime);
        System.out.println("getRoomsAvailable4.result=" + _getRoomsAvailable4__return);


        }
        {
        System.out.println("Invoking getAreas...");
        java.lang.String _getAreas_userName = "";
        java.lang.String _getAreas_password = "";
        int _getAreas_areaID = 0;
        java.lang.String _getAreas__return = port.getAreas(_getAreas_userName, _getAreas_password, _getAreas_areaID);
        System.out.println("getAreas.result=" + _getAreas__return);


        }
        {
        System.out.println("Invoking getCategoryStates...");
        java.lang.String _getCategoryStates_userName = "";
        java.lang.String _getCategoryStates_password = "";
        int _getCategoryStates_categoryID = 0;
        java.lang.String _getCategoryStates__return = port.getCategoryStates(_getCategoryStates_userName, _getCategoryStates_password, _getCategoryStates_categoryID);
        System.out.println("getCategoryStates.result=" + _getCategoryStates__return);


        }
        {
        System.out.println("Invoking updateWebUser...");
        java.lang.String _updateWebUser_userName = "";
        java.lang.String _updateWebUser_password = "";
        int _updateWebUser_webUserID = 0;
        java.lang.String _updateWebUser_webUserName = "";
        java.lang.String _updateWebUser_emailAddress = "";
        java.lang.String _updateWebUser_phone = "";
        java.lang.String _updateWebUser_fax = "";
        java.lang.String _updateWebUser_externalReference = "";
        java.lang.String _updateWebUser_networkID = "";
        int _updateWebUser_timeZoneID = 0;
        int _updateWebUser_statusID = 0;
        int _updateWebUser_webSecurityTemplateID = 0;
        service.web.api.ems.dea.ArrayOfInt _updateWebUser_webProcessTemplates = null;
        service.web.api.ems.dea.ArrayOfInt _updateWebUser_groups = null;
        boolean _updateWebUser_validated = false;
        java.lang.String _updateWebUser__return = port.updateWebUser(_updateWebUser_userName, _updateWebUser_password, _updateWebUser_webUserID, _updateWebUser_webUserName, _updateWebUser_emailAddress, _updateWebUser_phone, _updateWebUser_fax, _updateWebUser_externalReference, _updateWebUser_networkID, _updateWebUser_timeZoneID, _updateWebUser_statusID, _updateWebUser_webSecurityTemplateID, _updateWebUser_webProcessTemplates, _updateWebUser_groups, _updateWebUser_validated);
        System.out.println("updateWebUser.result=" + _updateWebUser__return);


        }
        {
        System.out.println("Invoking validateBilling...");
        java.lang.String _validateBilling_userName = "";
        java.lang.String _validateBilling_password = "";
        java.lang.String _validateBilling_billingReference = "";
        java.lang.String _validateBilling_poNumber = "";
        java.lang.String _validateBilling__return = port.validateBilling(_validateBilling_userName, _validateBilling_password, _validateBilling_billingReference, _validateBilling_poNumber);
        System.out.println("validateBilling.result=" + _validateBilling__return);


        }
        {
        System.out.println("Invoking getUDFListItems...");
        java.lang.String _getUDFListItems_userName = "";
        java.lang.String _getUDFListItems_password = "";
        java.lang.String _getUDFListItems__return = port.getUDFListItems(_getUDFListItems_userName, _getUDFListItems_password);
        System.out.println("getUDFListItems.result=" + _getUDFListItems__return);


        }
        {
        System.out.println("Invoking addBooking...");
        java.lang.String _addBooking_userName = "";
        java.lang.String _addBooking_password = "";
        int _addBooking_reservationID = 0;
        int _addBooking_roomID = 0;
        javax.xml.datatype.XMLGregorianCalendar _addBooking_bookingDate = null;
        javax.xml.datatype.XMLGregorianCalendar _addBooking_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addBooking_endTime = null;
        java.lang.String _addBooking_eventName = "";
        int _addBooking_statusID = 0;
        int _addBooking_eventTypeID = 0;
        java.lang.String _addBooking__return = port.addBooking(_addBooking_userName, _addBooking_password, _addBooking_reservationID, _addBooking_roomID, _addBooking_bookingDate, _addBooking_startTime, _addBooking_endTime, _addBooking_eventName, _addBooking_statusID, _addBooking_eventTypeID);
        System.out.println("addBooking.result=" + _addBooking__return);


        }
        {
        System.out.println("Invoking getAllRoomBookings...");
        java.lang.String _getAllRoomBookings_userName = "";
        java.lang.String _getAllRoomBookings_password = "";
        javax.xml.datatype.XMLGregorianCalendar _getAllRoomBookings_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getAllRoomBookings_endDate = null;
        int _getAllRoomBookings_roomID = 0;
        boolean _getAllRoomBookings_viewComboRoomComponents = false;
        java.lang.String _getAllRoomBookings__return = port.getAllRoomBookings(_getAllRoomBookings_userName, _getAllRoomBookings_password, _getAllRoomBookings_startDate, _getAllRoomBookings_endDate, _getAllRoomBookings_roomID, _getAllRoomBookings_viewComboRoomComponents);
        System.out.println("getAllRoomBookings.result=" + _getAllRoomBookings__return);


        }
        {
        System.out.println("Invoking addUDF...");
        java.lang.String _addUDF_userName = "";
        java.lang.String _addUDF_password = "";
        int _addUDF_parentLevelID = 0;
        int _addUDF_parentID = 0;
        int _addUDF_udfDefID = 0;
        java.lang.String _addUDF_udfValue = "";
        java.lang.String _addUDF__return = port.addUDF(_addUDF_userName, _addUDF_password, _addUDF_parentLevelID, _addUDF_parentID, _addUDF_udfDefID, _addUDF_udfValue);
        System.out.println("addUDF.result=" + _addUDF__return);


        }
        {
        System.out.println("Invoking getGroups...");
        java.lang.String _getGroups_userName = "";
        java.lang.String _getGroups_password = "";
        java.lang.String _getGroups_groupName = "";
        java.lang.String _getGroups_emailAddress = "";
        java.lang.String _getGroups__return = port.getGroups(_getGroups_userName, _getGroups_password, _getGroups_groupName, _getGroups_emailAddress);
        System.out.println("getGroups.result=" + _getGroups__return);


        }
        {
        System.out.println("Invoking addPayment...");
        java.lang.String _addPayment_userName = "";
        java.lang.String _addPayment_password = "";
        javax.xml.datatype.XMLGregorianCalendar _addPayment_transactionDate = null;
        int _addPayment_paymentTypeID = 0;
        java.lang.String _addPayment_checkNo = "";
        java.math.BigDecimal _addPayment_paymentAmount = new java.math.BigDecimal("0");
        java.lang.String _addPayment_invoiceNo = "";
        java.lang.String _addPayment_notes = "";
        java.lang.String _addPayment__return = port.addPayment(_addPayment_userName, _addPayment_password, _addPayment_transactionDate, _addPayment_paymentTypeID, _addPayment_checkNo, _addPayment_paymentAmount, _addPayment_invoiceNo, _addPayment_notes);
        System.out.println("addPayment.result=" + _addPayment__return);


        }
        {
        System.out.println("Invoking getCommentTypes...");
        java.lang.String _getCommentTypes_userName = "";
        java.lang.String _getCommentTypes_password = "";
        java.lang.String _getCommentTypes__return = port.getCommentTypes(_getCommentTypes_userName, _getCommentTypes_password);
        System.out.println("getCommentTypes.result=" + _getCommentTypes__return);


        }
        {
        System.out.println("Invoking getBuildings...");
        java.lang.String _getBuildings_userName = "";
        java.lang.String _getBuildings_password = "";
        java.lang.String _getBuildings__return = port.getBuildings(_getBuildings_userName, _getBuildings_password);
        System.out.println("getBuildings.result=" + _getBuildings__return);


        }
        {
        System.out.println("Invoking deleteServiceOrderDetail...");
        java.lang.String _deleteServiceOrderDetail_userName = "";
        java.lang.String _deleteServiceOrderDetail_password = "";
        int _deleteServiceOrderDetail_serviceOrderDetailID = 0;
        java.lang.String _deleteServiceOrderDetail__return = port.deleteServiceOrderDetail(_deleteServiceOrderDetail_userName, _deleteServiceOrderDetail_password, _deleteServiceOrderDetail_serviceOrderDetailID);
        System.out.println("deleteServiceOrderDetail.result=" + _deleteServiceOrderDetail__return);


        }
        {
        System.out.println("Invoking deleteServiceOrder...");
        java.lang.String _deleteServiceOrder_userName = "";
        java.lang.String _deleteServiceOrder_password = "";
        int _deleteServiceOrder_serviceOrderID = 0;
        java.lang.String _deleteServiceOrder__return = port.deleteServiceOrder(_deleteServiceOrder_userName, _deleteServiceOrder_password, _deleteServiceOrder_serviceOrderID);
        System.out.println("deleteServiceOrder.result=" + _deleteServiceOrder__return);


        }
        {
        System.out.println("Invoking updateWebUserOptions...");
        java.lang.String _updateWebUserOptions_userName = "";
        java.lang.String _updateWebUserOptions_password = "";
        int _updateWebUserOptions_webUserID = 0;
        int _updateWebUserOptions_webProcessTemplateID = 0;
        java.lang.String _updateWebUserOptions_optionName = "";
        java.lang.String _updateWebUserOptions_optionValue = "";
        java.lang.String _updateWebUserOptions__return = port.updateWebUserOptions(_updateWebUserOptions_userName, _updateWebUserOptions_password, _updateWebUserOptions_webUserID, _updateWebUserOptions_webProcessTemplateID, _updateWebUserOptions_optionName, _updateWebUserOptions_optionValue);
        System.out.println("updateWebUserOptions.result=" + _updateWebUserOptions__return);


        }
        {
        System.out.println("Invoking autoCheckin...");
        java.lang.String _autoCheckin_userName = "";
        java.lang.String _autoCheckin_password = "";
        java.lang.String _autoCheckin_emailAddress = "";
        int _autoCheckin_webUserID = 0;
        int _autoCheckin_udfid = 0;
        java.lang.String _autoCheckin_udfValue = "";
        int _autoCheckin_buildingID = 0;
        int _autoCheckin_roomID = 0;
        int _autoCheckin_floorID = 0;
        javax.xml.datatype.XMLGregorianCalendar _autoCheckin_bookingDate = null;
        int _autoCheckin_eventType = 0;
        java.lang.String _autoCheckin__return = port.autoCheckin(_autoCheckin_userName, _autoCheckin_password, _autoCheckin_emailAddress, _autoCheckin_webUserID, _autoCheckin_udfid, _autoCheckin_udfValue, _autoCheckin_buildingID, _autoCheckin_roomID, _autoCheckin_floorID, _autoCheckin_bookingDate, _autoCheckin_eventType);
        System.out.println("autoCheckin.result=" + _autoCheckin__return);


        }
        {
        System.out.println("Invoking getFeatures...");
        java.lang.String _getFeatures_userName = "";
        java.lang.String _getFeatures_password = "";
        int _getFeatures_buildingID = 0;
        java.lang.String _getFeatures__return = port.getFeatures(_getFeatures_userName, _getFeatures_password, _getFeatures_buildingID);
        System.out.println("getFeatures.result=" + _getFeatures__return);


        }

        System.exit(0);
    }

}
