/*
 *     Percussion CMS
 *     Copyright (C) 1999-2020 Percussion Software, Inc.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     Mailing Address:
 *
 *      Percussion Software, Inc.
 *      PO Box 767
 *      Burlington, MA 01803, USA
 *      +01-781-438-9900
 *      support@percussion.com
 *      https://www.percussion.com
 *
 *     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
 */
package com.percussion.services.publisher.data;

import com.percussion.services.assembly.jexl.PSLocationUtils;
import com.percussion.services.filter.data.PSFilterItem;
import com.percussion.utils.guid.IPSGuid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * One item to add to the content list. This class is used by the template
 * expander {@link com.percussion.services.publisher.IPSTemplateExpander} to 
 * communicate to the content list generator.
 * 
 * @author dougrand
 *
 */
public class PSContentListItem extends PSFilterItem
{
   /**
    * Used for generating pub locations
    */
   private static PSLocationUtils ms_locationutils = null;
   
   /**
    * The template to use with the item
    */
   private IPSGuid m_templateId;
   
   /**
    * The content 
    */
   private int m_deliveryContextId;
   
   /**
    * The location, calculated on construction
    */
   private String m_location;
   
   /**
    * For overriding subclasses that do not
    * want to use the public constructor.
    */
   protected PSContentListItem() 
   {
   }
   
   /**
    * Constructor.
    * @param cid the content GUID, never <code>null</code>
    * @param fid the folder GUID, may be <code>null</code>. The folder GUID
    * is typically a content GUID with a revision of <code>0</code>.
    * @param tid the template GUID, never <code>null</code>
    * @param siteid the site id, may be <code>null</code>
    * @param deliveryContextId the delivery context
    */
   public PSContentListItem(IPSGuid cid, IPSGuid fid, IPSGuid tid,
         IPSGuid siteid, int deliveryContextId)
   {
      super(cid, fid, siteid);
      if (tid == null)
      {
         throw new IllegalArgumentException("tid may not be null");
      }
      m_templateId = tid;
      m_deliveryContextId = deliveryContextId;
      m_location = null;
   }
   
   //see base class
   @Override
   public PSContentListItem clone()
   {
      return (PSContentListItem)super.clone();
   }

   /**
    * @return Returns the contentId.
    * @deprecated use {@link #getItemId()} instead.
    */
   public IPSGuid getContentId()
   {
      return getItemId();
   }

   /**
    * @return Returns the templateId.
    */
   public IPSGuid getTemplateId()
   {
      return m_templateId;
   }
   
   public void setTemplateId(IPSGuid templateId) {
      this.m_templateId = templateId;
   }

   /**
    * The ID of the delivery context.
    * @return Returns the ID of the delivery context.
    */
   public int getContext()
   {
      return m_deliveryContextId;
   }
   
   public void setContext(int contextId) {
      this.m_deliveryContextId = contextId;
   }

   /**
    * The delivery location which is typically generated by location generator.
    * @return the delivery location, which is relative to the publish root if
    * the target site.
    */
   public String getLocation()
   {
      if (m_location == null)
      {
         m_location = getLocationUtils().generate(this);
      }
      return m_location;
   }
   
   /**
    * Set the delivery location, used to set the location externally as is done 
    * for the unpublish location.
    * @param location the delivery location, never <code>null</code> or empty
    */
   public void setLocation(String location)
   {
      if (StringUtils.isBlank(location))
      {
         throw new IllegalArgumentException("location may not be null or empty");
      }
      m_location = location;
   }
   

   /** (non-Javadoc)
    * @see java.lang.Object#equals(java.lang.Object)
    */
   @Override
   public boolean equals(Object arg0)
   {
      return EqualsBuilder.reflectionEquals(this, arg0);
   }
   
   /** (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   @Override
   public int hashCode()
   {
      return HashCodeBuilder.reflectionHashCode(this);
   }
   
   /** (non-Javadoc)
    * @see java.lang.Object#toString()
    */
   @Override
   public String toString()
   {
      return ToStringBuilder.reflectionToString(this);
   }
   
   /**
    * Lookup location utils on demand
    * 
    * @return location utils, never <code>null</code>
    */
   private PSLocationUtils getLocationUtils()
   {
      if (ms_locationutils == null)
      {
         ms_locationutils = new PSLocationUtils();
      }
      return ms_locationutils;
   }
}
