/*
 * Copyright 1999-2023 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.percussion.services.publisher.data;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PsxEditionTaskParam generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "PSX_EDITION_TASK_PARAM")
public class PSEditionTaskParam implements java.io.Serializable
{
   /**
    * Required serial number for serialized objects. 
    */
   private static final long serialVersionUID = 2251286993400776508L;

   /**
    * The id of the specific parameter.
    */
   @Id
   private Long taskParamId;
   
   /**
    * The foreign key of the owning
    */
   @Basic
   @Column(name = "TASK_ID")
   private Long taskId;
   
   /**
    * Hibernate version column
    */
   @Version
   Integer version;

   /**
    * The name of the property, unique for a given task.
    */
   @Basic
   private String name;

   /**
    * The value of the property
    */
   @Basic
   private String value;

   /**
    * Ctor
    */
   public PSEditionTaskParam() {
   }

   /**
    * The id of this task parameter.
    * 
    * @return the id, never <code>null</code> for a persisted object.
    */
   public Long getTaskParamId()
   {
      return this.taskParamId;
   }

   /**
    * Set the id of this task parameter.
    * @param taskParamId the id, never <code>null</code>.
    */
   public void setTaskParamId(Long taskParamId)
   {
      if (taskParamId == null)
      {
         throw new IllegalArgumentException("taskParamId may not be null");
      }
      this.taskParamId = taskParamId;
   }

   /**
    * Get the id of the parent task.
    * 
    * @return the id of the parent task, never <code>null</code> for a parameter
    * that is saved and connected to a task.
    */
   public Long getTaskId()
   {
      return this.taskId;
   }

   /**
    * Set the task id.
    * 
    * @param taskId the task id, might be <code>null</code> to disconnect a 
    * parameter from a task.
    */
   public void setTaskId(Long taskId)
   {
      this.taskId = taskId;
   }

   /**
    * Get the name of the parameter.
    * @return the name, never <code>null</code> or empty for a saved instance.
    */
   public String getName()
   {
      return this.name;
   }

   /**
    * Set the name.
    * @param name the name, never <code>null</code> or empty.
    */
   public void setName(String name)
   {
      if (StringUtils.isBlank(name))
      {
         throw new IllegalArgumentException(
               "name may not be null or empty");
      }
      this.name = name;
   }

   /**
    * Get the value of the parameter.
    * @return the value
    */
   public String getValue()
   {
      return this.value;
   }

   /**
    * Set the value of the parameter.
    * 
    * @param value the value, <code>null</code> or empty values will be removed.
    */
   public void setValue(String value)
   {
      this.value = value;
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#equals(java.lang.Object)
    */
   @Override
   public boolean equals(Object obj)
   {
      if (!(obj instanceof PSEditionTaskParam))
         return false;
      PSEditionTaskParam etp = (PSEditionTaskParam) obj;
      
      EqualsBuilder builder = new EqualsBuilder()
         .append(taskParamId, etp.taskParamId)
         .append(taskId, etp.taskId)
         .append(version, etp.version)
         .append(name, etp.name)
         .append(value, etp.value);

      return builder.isEquals();
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   @Override
   public int hashCode()
   {
      return new HashCodeBuilder().append(name).toHashCode();
   }
}
