#! /bin/sh
#
#     Percussion CMS
#     Copyright (C) 1999-2020 Percussion Software, Inc.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     Mailing Address:
#
#      Percussion Software, Inc.
#      PO Box 767
#      Burlington, MA 01803, USA
#      +01-781-438-9900
#      support@percussion.com
#      https://www.percusssion.com
#
#     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
#


SERVER_DIR=

export SERVER_DIR

HOSTHNAME=`hostname`

#Our ftsdaemon does not have a stop or start BUT it is a daemon- blink blink
StopRhythmyxFTSServer () 
{
  groupPID=`pgrep -f "RhythmyxFTSD start"`  
  pkill -g $groupPID
}

StartRhythmyxFTSServer() 
{
  curDir=`pwd`
  cd $SERVER_DIR
  $SERVER_DIR/bin/RhythmyxProcessDaemon.bin
  cd $curDir
}


case "$1" in
'start')
        StartRhythmyxFTSServer
 	;;
'stop')
        StopRhythmyxFTSServer            
	;;
*)
	echo "Usage: /etc/init.d/RhythmyxFTSD { start | stop }"
	;;
esac
