/*
 *     Percussion CMS
 *     Copyright (C) 1999-2020 Percussion Software, Inc.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     Mailing Address:
 *
 *      Percussion Software, Inc.
 *      PO Box 767
 *      Burlington, MA 01803, USA
 *      +01-781-438-9900
 *      support@percussion.com
 *      https://www.percussion.com
 *
 *     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
 */

package com.percussion.cx;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import java.util.Arrays;
import java.util.Collection;
import java.util.Iterator;

public class PSOptionManagerConstants {

    /**
        * This value is the key whose values are the persisted options in the
        * the session object.
        */
       public final static String SESSIONOBJECT_CXOPTIONS = "cxoptions";
    /**
        * This value is used to get the options from the session object, this
        * is the value of a {@link #IPSHTMLParameter.SYS_COMMAND } key.
        */
       public final static String LOAD_COMMAND = "get";
    /**
        * This value is used to explicitely get the default options from the system.
        * This is the value of a {@link #IPSHTMLParameter.SYS_COMMAND } key.
        */
       public final static String LOAD_DEFAULT = "default";
    /**
        * This value is used to put the options into the session object, this
        * is the value of a {@link #IPSHTMLParameter.SYS_COMMAND } key.
        */
       public final static String SAVE_COMMAND = "put";
    /**
        * This toXml's all objects in the collection and appends the element
        * returned by the call to <code>el</code>. Collections must of type
        * <code>IPSClientObjects</code>, this simply iterates through the collection
        * calling toXml on each.
        *
        * @param el - on which to append the elements generated by the call to
        * each
        * {@link IPSClientObjects#toXml(Document) IPSClientObjects.toXml(Document)}
        * , must not be <code>null</code>.
        * @param doc - on which to create elements, must not be <code>null</code>.
        * @param col - must not be <code>null</code>, must contain objects of
        * <code>IPSClientObjects</code>, may be empty.
        */
       public  static void toXmlCollection(Element el, Document doc, Collection col)
       {
          if (el == null || doc == null || col == null)
             throw new IllegalArgumentException("arguments must not be null");
    
          Iterator it = col.iterator();
          IPSClientObjects comp = null;
          while (it.hasNext())
          {
             Object o = it.next();
             if (!(o instanceof IPSClientObjects))
                throw new IllegalArgumentException("Collection must contain only IPSClientObjects values");
    
             comp = (IPSClientObjects)o;
             el.appendChild(comp.toXml(doc));
          }
       }
    /**
        * @todo is there a utils package that has this?
        * Compares objects that implement the <code>equals()</code> method.
        * <code>String</code>s will be compared with case ignored.
        * Are they equal?
        *
        * @param a an object to compare
        * @param b an object to compare
        * @return <code>true</code>if they are, otherwise <code>false</code>.
        */
       public static boolean compare(Object a, Object b)
       {
          if (a == null || b == null)
          {
             if (a != null || b != null)
                return false;
          }
          else
          {
             if (a.getClass().isArray() && b.getClass().isArray())
                return Arrays.equals((Object[])a, (Object[])b);
             if (a instanceof String && b instanceof String)
                return ((String)a).equalsIgnoreCase((String)b);
             if (!a.equals(b))
                return false;
          }
          return true;
       }

}
