/*
 *     Percussion CMS
 *     Copyright (C) 1999-2020 Percussion Software, Inc.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     Mailing Address:
 *
 *      Percussion Software, Inc.
 *      PO Box 767
 *      Burlington, MA 01803, USA
 *      +01-781-438-9900
 *      support@percussion.com
 *      https://www.percusssion.com
 *
 *     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
 */
package com.percussion.xmldom;

import com.percussion.extension.IPSResultDocumentProcessor;
import com.percussion.extension.PSDefaultExtension;
import com.percussion.extension.PSExtensionProcessingException;
import com.percussion.extension.PSParameterMismatchException;
import com.percussion.server.IPSRequestContext;
import com.percussion.xml.PSXmlTreeWalker;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

/**
 * A Rhythmyx post-exit that removes un-necessary nodes from the XML result
 * document.
 * <p>
 * The result document is generated by the server in response to a query. When
 * this document contains text data that must be converted into XML nodes, the
 * text representation is no longer needed. While these nodes do not harm
 * anything, they greatly enlarge the result document, and make debugging of the
 * XML difficult.
 * <p>
 * This exit takes a series of parameters: the names of the nodes that must be
 * removed.  Any number of nodes may be specified.  Node names are relative to
 * the <code>&lt;root element&gt;</code>. The root element name is never
 * included in the path name.
**/
public class PSXdRemoveElements  extends PSDefaultExtension implements IPSResultDocumentProcessor
{

 /**
  * This method handles the post-exit request.
  *
  * @param params an array of objects representing the parameters. See the
  * description under {@link PSXdDomToText} for parameter details.
  *
  * @param request the request context for this request
  *
  * @param resultDoc the XML document resulting from the Rhythmyx server
  * operation.  The output text will be added as an XML node in this document.
  *
  * @throws PSExtensionProcessingException when a run time error is detected.
  *
  **/
  public org.w3c.dom.Document processResultDocument(Object[] params,
           IPSRequestContext request, Document resultDoc)
             throws PSParameterMismatchException, PSExtensionProcessingException
    {
     if ( params.length < 1) {
         throw new PSParameterMismatchException(0,1);
         }
      if ( null == params[0] || 0 == params[0].toString().trim().length())
      {
         throw new PSExtensionProcessingException( 0, "Empty or null Element Name." );
      }

      for(int i=0; i < params.length; i++) {
         String sourceNodeName = params[i].toString();
         if(sourceNodeName.trim().length() == 0) {
            request.printTraceMessage("Empty node name encountered");
            continue;
            }
         PSXmlTreeWalker nodeWalker = new PSXmlTreeWalker(resultDoc);
         Element docRoot = (Element)nodeWalker.getCurrent();
         Element elementNode = nodeWalker.getNextElement(sourceNodeName,
                            nodeWalker.GET_NEXT_ALLOW_CHILDREN);

         if(null == elementNode) {
            request.printTraceMessage("Element not found:" + sourceNodeName);
            continue;
            }


         Node parentNode = elementNode.getParentNode();
         if(null == parentNode) {
             request.printTraceMessage("Element has no parent:" + sourceNodeName);
             continue;
          }

         parentNode.removeChild(elementNode);
         } //for

      return resultDoc;
    }

 /**
  * This exit will never modify the stylesheet.
  **/

  public boolean canModifyStyleSheet()
    {
     return false;
    }
}
