/*
 * Copyright 1999-2023 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.percussion.search;

import com.percussion.extension.IPSExtension;
import com.percussion.extension.PSExtensionProcessingException;
import com.percussion.server.IPSRequestContext;

import java.util.List;

/**
 * This interface is implemented by extensions capable of processing the search
 * result rows.
 * <p>
 * The search handler will construct an instance of this class and run it to
 * post process the search results that were generated by the search handler.
 * The implementing class can modify column values for each search result row.
 * It can add additional row(s) by cloning row(s). However,
 * <ul>
 * <li>it cannot add or delete columns to a row</li>
 * <li>it cannot add a new row without cloning an existing one.</li>
 * </ul>
 * <p>
 * <em>The implementation of this extension must be thread safe.</em>
 */
public interface IPSSearchResultsProcessor extends IPSExtension
{
   /**
    * The actual implementation of the row processing as described in the class
    * description.
    * 
    * @param params parameters to the extension as documented in the definition
    *           of the extension. Never <code>null</code>, may be empty.
    * @param rows a list of the search result
    *           {@link com.percussion.search.IPSSearchResultRow rows}, These
    *           are the rows the implementer may want to modify. Never
    *           <code>null</code> or empty.
    * @param request request context object, never <code>null</code>.
    * @return A list of modified rows. Must not be <code>null</code> may be
    *         empty.
    * @throws PSExtensionProcessingException implementation can throw this
    *            exception if any error occurs during processing.
    */
   List processRows(Object[] params, List rows, IPSRequestContext request)
         throws PSExtensionProcessingException;
}
