/*
 * Copyright 1999-2023 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.percussion.soln.utilities.rx.udf;

import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLEncoder;

import com.percussion.data.PSConversionException;
import com.percussion.extensions.general.PSMakeAbsLink;
import com.percussion.server.IPSRequestContext;

public class MakeAbsLinkEncoded extends PSMakeAbsLink {

    /**
     * URI Encodes the links generated by {@link PSMakeAbsLink}.
     * <em>See the Extensions.xml for more Documentation.</em>
     * @see com.percussion.extensions.general.PSMakeAbsLink#processUdf(java.lang.Object[], com.percussion.server.IPSRequestContext)
     */
    @Override
    public String processUdf(Object[] params, IPSRequestContext request) throws PSConversionException {
        URL link = (URL) super.processUdf(params, request);
        try {
            return URLEncoder.encode(link.toString(), "UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException("This is a coding error", e);
        }
    }
    

}
