package com.percussion.soln.utilities.rx.udf;

import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLEncoder;

import com.percussion.data.PSConversionException;
import com.percussion.extensions.general.PSMakeAbsLink;
import com.percussion.server.IPSRequestContext;

public class MakeAbsLinkEncoded extends PSMakeAbsLink {

    /**
     * URI Encodes the links generated by {@link PSMakeAbsLink}.
     * <em>See the Extensions.xml for more Documentation.</em>
     * @see com.percussion.extensions.general.PSMakeAbsLink#processUdf(java.lang.Object[], com.percussion.server.IPSRequestContext)
     */
    @Override
    public String processUdf(Object[] params, IPSRequestContext request) throws PSConversionException {
        URL link = (URL) super.processUdf(params, request);
        try {
            return URLEncoder.encode(link.toString(), "UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException("This is a coding error", e);
        }
    }
    

}
