/*
 * Copyright 1999-2023 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.16 at 05:46:39 PM ART 
//


package com.percussion.delivery.service.impl;
import com.percussion.share.data.PSAbstractDataObject;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DeliveryServer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryServer">
 *   &lt;complexContent>
 *     &lt;extension base="{}PSAbstractDataObject">
 *       &lt;sequence>
 *         &lt;element name="server-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connection-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="encrypted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="admin-connection-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allow-self-signed-certificate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="availableServices" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryServer", propOrder = {
    "serverType",
    "connectionUrl",
    "user",
    "password",
    "adminConnectionUrl",
    "allowSelfSignedCertificate",
    "availableServices"
})
public class DeliveryServer
    extends PSAbstractDataObject
{
    @XmlElement(name = "server-type", required = true)
    protected String serverType;
    @XmlElement(name = "connection-url", required = true)
    protected String connectionUrl;
    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected DeliveryServer.Password password;
    @XmlElement(name = "admin-connection-url", required = true)
    protected String adminConnectionUrl;
    @XmlElement(name = "allow-self-signed-certificate")
    protected boolean allowSelfSignedCertificate;
    protected List<DeliveryServer.AvailableServices> availableServices;

    /**
     * Gets the value of the connectionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionUrl() {
        if(connectionUrl != null && connectionUrl.trim()!=""){
            //Chop off the training slash if present as it causes problems
            if(connectionUrl.endsWith("/")){
                connectionUrl = connectionUrl.substring(0,connectionUrl.length()-1);
            }
        }
        return connectionUrl;
    }

    /**
     * Sets the value of the connectionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionUrl(String value) {
        this.connectionUrl = value;
    }

    /**
     * 
     * @return 
          possible object is
     *     {@link String }
     */
    public String getServerType() {
       return serverType;
   }

   /**
    * Sets the value of the connectionUrl property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setServerType(String value) {
       this.serverType = value;
   }
    
    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryServer.Password }
     *     
     */
    public DeliveryServer.Password getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryServer.Password }
     *     
     */
    public void setPassword(DeliveryServer.Password value) {
        this.password = value;
    }

    /**
     * Gets the value of the adminConnectionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminConnectionUrl() {
        if(adminConnectionUrl != null && adminConnectionUrl.trim()!=""){
            //Chop off the training slash if present as it causes problems
            if(adminConnectionUrl.endsWith("/")){
                adminConnectionUrl = adminConnectionUrl.substring(0,adminConnectionUrl.length()-1);
            }
        }
        return adminConnectionUrl;
    }

    /**
     * Sets the value of the adminConnectionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminConnectionUrl(String value) {
        this.adminConnectionUrl = value;
    }

    /**
     * Gets the value of the allowSelfSignedCertificate property.
     * 
     */
    public boolean getAllowSelfSignedCertificate() {
        return allowSelfSignedCertificate;
    }

    /**
     * Sets the value of the allowSelfSignedCertificate property.
     * 
     */
    public void setAllowSelfSignedCertificate(boolean value) {
        this.allowSelfSignedCertificate = value;
    }

    /**
     * Gets the value of the availableServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryServer.AvailableServices }
     * 
     * 
     */
    public List<DeliveryServer.AvailableServices> getAvailableServices() {
        if (availableServices == null) {
            availableServices = new ArrayList<>();
        }
        return this.availableServices;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class AvailableServices {

        protected List<String> service;

        /**
         * Gets the value of the service property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the service property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getService() {
            if (service == null) {
                service = new ArrayList<>();
            }
            return this.service;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="encrypted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Password {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Boolean encrypted;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the encrypted property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isEncrypted() {
            if (encrypted == null) {
                return false;
            } else {
                return encrypted;
            }
        }

        /**
         * Sets the value of the encrypted property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEncrypted(Boolean value) {
            this.encrypted = value;
        }

    }

}
