#! /bin/sh

SERVER_DIR=
export SERVER_DIR

JAVA_HOME="$SERVER_DIR"/JRE
export JAVA_HOME

CATALINA_HOME="$SERVER_DIR"
export CATALINA_HOME


cd $SERVER_DIR
#
# Find the tools
#
OS=`uname`
if [ "$OS" = "SunOS" ]; then
    AWK_PROG="/usr/bin/nawk"
    WHOAMI_PROG="/usr/ucb/whoami"
elif [ "$OS" = "Linux" ]; then
    AWK_PROG="/bin/gawk"
    WHOAMI_PROG="/usr/bin/whoami"
else
    # SHRUG!!
    AWK_PROG=/usr/bin/awk
    echo "BEFORE WHOAMI"
    WHOAMI_PROG="/usr/bin/whoami"
    echo "AFTER WHOAMI"
fi

#
# Get the current user.
#
getUser()
{
   echo " {                                 " > a.awk
   echo "   pos=index(\$1,\"uid=0(root)\"); " >> a.awk
   echo "   if( pos > 0 )                   " >> a.awk
   echo "     printf(\"root\");             " >> a.awk
   echo "   else                            " >> a.awk
   echo "     printf(\"other\");            " >> a.awk
   echo " }                                 " >> a.awk
   id > out.txt
   $AWK_PROG -f a.awk out.txt
}


USER=`getUser`

$WHOAMI_PROG > out.txt
cur_user=`$AWK_PROG '/^[^#]/' ./out.txt`
rm out.txt

rx_user=""

if [ -f  ../rx_user.id ] ; then
   echo " {                                 " > a.awk
   echo "     printf(SYSTEM_USER_ID);       " >> a.awk
   echo " }                                 " >> a.awk
   userid=`$AWK_PROG '/^[^#]/ && /SYSTEM_USER_ID=/' ../rx_user.id`
   id > out.txt
   rx_user=`$AWK_PROG -v $userid -f a.awk ./out.txt`
   rm a.awk
   rm out.txt
fi



MSG="Daemon is either not installed or SERVER_DIR property is not set correctly"


StopRhythmyxPublisherServer () 
{
   if [ "$SERVER_DIR" == "" ] ; then
        echo $MSG
  else
	if [ "$USER" = "root" ]; then
    	    su - $rx_user -c "$SERVER_DIR/bin/shutdown.sh";
	else
	    $SERVER_DIR/bin/shutdown.sh
	fi
  fi
}

StartRhythmyxPublisherServer() 
{
   if [ "$SERVER_DIR" == "" ] ; then
        echo $MSG
  else
	if [ "$USER" = "root" ]; then
    	    su - $rx_user -c "cd $SERVER_DIR/bin;$SERVER_DIR/bin/startup.sh";
	else
	    $SERVER_DIR/bin/startup.sh
	fi
  fi

}


case "$1" in
'start')
        StartRhythmyxPublisherServer
 	;;
'stop')
        StopRhythmyxPublisherServer            
	;;
*)
	echo "Usage: /etc/init.d/RhythmyxPublisherD { start | stop }"
	;;
esac


