#! /bin/sh

SERVER_DIR=

export SERVER_DIR

HOSTHNAME=`hostname`

#Our ftsdaemon does not have a stop or start BUT it is a daemon- blink blink
StopRhythmyxFTSServer () 
{
  groupPID=`pgrep -f "RhythmyxFTSD start"`  
  pkill -g $groupPID
}

StartRhythmyxFTSServer() 
{
  curDir=`pwd`
  cd $SERVER_DIR
  $SERVER_DIR/bin/RhythmyxProcessDaemon.bin
  cd $curDir
}


case "$1" in
'start')
        StartRhythmyxFTSServer
 	;;
'stop')
        StopRhythmyxFTSServer            
	;;
*)
	echo "Usage: /etc/init.d/RhythmyxFTSD { start | stop }"
	;;
esac
