#! /bin/sh
#
#     Percussion CMS
#     Copyright (C) 1999-2020 Percussion Software, Inc.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     Mailing Address:
#
#      Percussion Software, Inc.
#      PO Box 767
#      Burlington, MA 01803, USA
#      +01-781-438-9900
#      support@percussion.com
#      https://www.percusssion.com
#
#     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
#
SERVER_DIR=

SplitServerPath()
{
   if [ -f  ./RhythmyxTmp.awk ] ; then
      rm ./RhythmyxTmp.awk
   fi
   
   echo " {                                                         " > RhythmyxTmp.awk   
   echo "     cmd=\"\"                                              " >>RhythmyxTmp.awk
   echo "     if (ACTION==\"start\")                                " >>RhythmyxTmp.awk
   echo "     {                                                     " >>RhythmyxTmp.awk   
   echo "        cmd=\"/bin/RhythmyxDaemon start \"                 " >>RhythmyxTmp.awk
   echo "     }                                                     " >>RhythmyxTmp.awk
   echo "     if (ACTION==\"stop\")                                 " >>RhythmyxTmp.awk
   echo "     {                                                     " >>RhythmyxTmp.awk
   echo "        cmd=\"/bin/RhythmyxDaemon stop \"                  " >>RhythmyxTmp.awk
   echo "     }                                                     " >>RhythmyxTmp.awk
   echo "     n=split( serverDir, path, \":\" )                     " >>RhythmyxTmp.awk
   echo "     for ( i = 1; i <= n; ++i )                            " >>RhythmyxTmp.awk
   echo "     {                                                     " >>RhythmyxTmp.awk
   echo "        if( length (path[i] ) > 0)                         " >>RhythmyxTmp.awk
   echo "        {                                                  " >>RhythmyxTmp.awk 
   echo "             system(path[i] cmd path[i])                   " >>RhythmyxTmp.awk
   echo "        }                                                  " >>RhythmyxTmp.awk
   echo "     }                                                     " >>RhythmyxTmp.awk
   echo "  }                                                        " >>RhythmyxTmp.awk
}

id > RhythmyxOut.txt
SplitServerPath
nawk -v serverDir=$SERVER_DIR -v ACTION=$1 -f RhythmyxTmp.awk RhythmyxOut.txt
rm RhythmyxOut.txt
rm RhythmyxTmp.awk

