/*
 *     Percussion CMS
 *     Copyright (C) 1999-2020 Percussion Software, Inc.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     Mailing Address:
 *
 *      Percussion Software, Inc.
 *      PO Box 767
 *      Burlington, MA 01803, USA
 *      +01-781-438-9900
 *      support@percussion.com
 *      https://www.percusssion.com
 *
 *     You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 02:27:24 PM ACT 
//


package com.percussion.delivery.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="CommentService" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Comments">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="Comment">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="pagePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MembershipService">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Memberships">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="Membership">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ConfirmationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commentService",
    "membershipService"
})
@XmlRootElement(name = "DeliveryServicesContent")
public class DeliveryServicesContent {

    @XmlElement(name = "CommentService")
    protected DeliveryServicesContent.CommentService commentService;
    @XmlElement(name = "MembershipService")
    protected DeliveryServicesContent.MembershipService membershipService;

    /**
     * Gets the value of the commentService property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryServicesContent.CommentService }
     *     
     */
    public DeliveryServicesContent.CommentService getCommentService() {
        return commentService;
    }

    /**
     * Sets the value of the commentService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryServicesContent.CommentService }
     *     
     */
    public void setCommentService(DeliveryServicesContent.CommentService value) {
        this.commentService = value;
    }

    /**
     * Gets the value of the membershipService property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryServicesContent.MembershipService }
     *     
     */
    public DeliveryServicesContent.MembershipService getMembershipService() {
        return membershipService;
    }

    /**
     * Sets the value of the membershipService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryServicesContent.MembershipService }
     *     
     */
    public void setMembershipService(DeliveryServicesContent.MembershipService value) {
        this.membershipService = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Comments">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="Comment">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Body" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="pagePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comments"
    })
    public static class CommentService {

        @XmlElement(name = "Comments")
        protected List<DeliveryServicesContent.CommentService.Comments> comments;

        /**
         * Gets the value of the comments property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comments property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComments().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeliveryServicesContent.CommentService.Comments }
         * 
         * 
         */
        public List<DeliveryServicesContent.CommentService.Comments> getComments() {
            if (comments == null) {
                comments = new ArrayList<DeliveryServicesContent.CommentService.Comments>();
            }
            return this.comments;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="Comment">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Body" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="pagePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "comment"
        })
        public static class Comments {

            @XmlElement(name = "Comment", required = true)
            protected List<DeliveryServicesContent.CommentService.Comments.Comment> comment;
            @XmlAttribute(required = true)
            protected String pagePath;
            @XmlAttribute
            protected Integer count;

            /**
             * Gets the value of the comment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the comment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getComment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DeliveryServicesContent.CommentService.Comments.Comment }
             * 
             * 
             */
            public List<DeliveryServicesContent.CommentService.Comments.Comment> getComment() {
                if (comment == null) {
                    comment = new ArrayList<DeliveryServicesContent.CommentService.Comments.Comment>();
                }
                return this.comment;
            }

            /**
             * Gets the value of the pagePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPagePath() {
                return pagePath;
            }

            /**
             * Sets the value of the pagePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPagePath(String value) {
                this.pagePath = value;
            }

            /**
             * Gets the value of the count property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getCount() {
                if (count == null) {
                    return  1;
                } else {
                    return count;
                }
            }

            /**
             * Sets the value of the count property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCount(Integer value) {
                this.count = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Body" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "title",
                "email",
                "body",
                "username",
                "url"
            })
            public static class Comment {

                @XmlElement(name = "Title", required = true)
                protected String title;
                @XmlElement(name = "Email", required = true)
                protected String email;
                @XmlElement(name = "Body", required = true)
                protected String body;
                @XmlElement(name = "Username", required = true)
                protected String username;
                @XmlElement(name = "Url", required = true)
                protected String url;

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

                /**
                 * Gets the value of the body property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBody() {
                    return body;
                }

                /**
                 * Sets the value of the body property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBody(String value) {
                    this.body = value;
                }

                /**
                 * Gets the value of the username property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUsername() {
                    return username;
                }

                /**
                 * Sets the value of the username property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUsername(String value) {
                    this.username = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Memberships">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="Membership">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ConfirmationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memberships"
    })
    public static class MembershipService {

        @XmlElement(name = "Memberships")
        protected List<DeliveryServicesContent.MembershipService.Memberships> memberships;

        /**
         * Gets the value of the memberships property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the memberships property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMemberships().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeliveryServicesContent.MembershipService.Memberships }
         * 
         * 
         */
        public List<DeliveryServicesContent.MembershipService.Memberships> getMemberships() {
            if (memberships == null) {
                memberships = new ArrayList<DeliveryServicesContent.MembershipService.Memberships>();
            }
            return this.memberships;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="Membership">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ConfirmationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "membership"
        })
        public static class Memberships {

            @XmlElement(name = "Membership", required = true)
            protected List<DeliveryServicesContent.MembershipService.Memberships.Membership> membership;

            /**
             * Gets the value of the membership property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the membership property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMembership().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DeliveryServicesContent.MembershipService.Memberships.Membership }
             * 
             * 
             */
            public List<DeliveryServicesContent.MembershipService.Memberships.Membership> getMembership() {
                if (membership == null) {
                    membership = new ArrayList<DeliveryServicesContent.MembershipService.Memberships.Membership>();
                }
                return this.membership;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ConfirmationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "emailAddress",
                "password",
                "confirmationRequired"
            })
            public static class Membership {

                @XmlElement(name = "EmailAddress", required = true)
                protected String emailAddress;
                @XmlElement(name = "Password", required = true)
                protected String password;
                @XmlElement(name = "ConfirmationRequired")
                protected boolean confirmationRequired;

                /**
                 * Gets the value of the emailAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailAddress() {
                    return emailAddress;
                }

                /**
                 * Sets the value of the emailAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailAddress(String value) {
                    this.emailAddress = value;
                }

                /**
                 * Gets the value of the password property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPassword() {
                    return password;
                }

                /**
                 * Sets the value of the password property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPassword(String value) {
                    this.password = value;
                }

                /**
                 * Gets the value of the confirmationRequired property.
                 * 
                 */
                public boolean isConfirmationRequired() {
                    return confirmationRequired;
                }

                /**
                 * Sets the value of the confirmationRequired property.
                 * 
                 */
                public void setConfirmationRequired(boolean value) {
                    this.confirmationRequired = value;
                }

            }

        }

    }

}
